apiVersion: 1
datasources:
  - name: InfluxDB Flux
    type: influxdb
    access: proxy
    database: db0
    url: http://influxdb:8086
    isDefault: true
    editable: true
    jsonData:
      version: Flux
      organization: vrlabs
      defaultBucket: telemetry
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
